name: "Manage JSON Packages via GitHub Variables or File"
description: "Action to manage a packages.json file either stored as a GitHub Variable or as a file in the repository. Supports retrieving package information, adding/updating/removing package entries, and counting packages. Can set outputs for use in subsequent steps and optionally save updates back to the variable or file."
author: "DCx7C5"

branding:
  icon: "package"
  color: "blue"


inputs:
  var-name:
    required: false
    description: "Name of variable that stores JSON package dictionary (default: JSON_PACKAGES)."
    default: 'JSON_PACKAGES'
  pkg-name:
    required: false
    description: "New-line separated list of package names to manage. For 'get' action, retrieves details for the specified packages; for 'add', 'update', and 'remove' actions, specifies the package(s) to modify."
    default: ''
  key:
    required: false
    description: "New-line separated list of keys to add/update/remove for the specified package(s). Used for add/update/remove actions."
    default: ''
  value:
    required: false
    description: "New-line separated list of values corresponding to the keys for add/update actions. For remove action, this input is ignored. If the value is a valid JSON string, it will be parsed as JSON; otherwise, it will be treated as a plain string."
    default: ''
  env:
    required: false
    description: "Set deployment environment variable"
    default: ''
  org:
    required: false
    description: "Name of the organisation to store the variable in (defaults to current organisation based on variable_type)"
    default: ''
  repo:
    required: false
    description: "Set repository variable (defaults to current repository)"
    default: ''
  gh-token:
    required: false
    description: "GitHub Token with permissions to manage secrets (usually GITHUB_TOKEN)"
    default: ''
  output-structure:
    required: false
    description: "Output structure for retrieved package information (only for 'get' action, can be either 'dict' or 'list', defaults to 'dict')."
    default: 'dict'
  action:
    required: false
    default: 'get'
    description: >-
      Action to perform on the packages dictionary. Valid actions are:
      - get: Retrieve package information. If pkg_name is provided, retrieves details for that package; otherwise, retrieves the entire packages.json content.
      - add: Add a new package entry. Requires pkg_name, key, and value inputs.
      - update: Update an existing package entry. Requires pkg_name, key, and value inputs.
      - remove: Remove a package entry. Requires  pkg_name input.
      - count: Count the number of packages in the dictionary.


outputs:
  out:
    description: "Output channel for the action. "
    value: ${{ steps.convert_output.outputs.out || steps.build_get_args.outputs.out || steps.build_add_args.outputs.out || steps.build_del_args.outputs.out }}
  debug-args:
    description: "Debug output containing the generated jq filter and arguments for troubleshooting (only if 'step_summary' input is set to 'true')."
    value: ${{ steps.build_get_args.outputs.args || steps.build_add_args.outputs.args || steps.build_del_args.outputs.args }}
  debug-filter:
    description: "Debug output containing the generated jq filter for troubleshooting (only if 'step_summary' input is set to 'true')."
    value: ${{ steps.build_get_args.outputs.filter || steps.build_add_args.outputs.filter || steps.build_del_args.outputs.filter }}


runs:
  using: composite

  steps:
    - id: validate_inputs
      shell: bash
      env:
        JSON_VAR_NAME: "${{ inputs.var-name }}"
        GH_TOKEN: "${{ inputs.gh-token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
        ACTION: "${{ inputs.action }}"
        INPUT_PKGNAMES: "${{ inputs.pkg-name }}"
        INPUT_KEYS: "${{ inputs.key }}"
        INPUT_VALUES: "${{ inputs.value }}"
      run: |
        
        if [[ ! "$ACTION" =~ ^(get|add|update|remove|count|delete)$ ]]; then
          echo "::error::Invalid action '${ACTION}'. Valid actions are: ${valid_actions[*]}" >&2
          exit 1
        fi
        
        count=0
        [ -n "${{ inputs.env }}" ] && ((count+=1))
        [ -n "${{ inputs.repo }}" ] && ((count+=1))
        [ -n "${{ inputs.org }}" ] && ((count+=1))
        
        if (( count > 1 )); then
          echo "::error::Not more than one of 'env', 'repo' or 'org' can be set to a non-empty value" >&2
          exit 1
        fi
        
        if [[ -n "${{ inputs.key }}" && -n "${{ inputs.value }}" && ! "$ACTION" =~ ^(add|update|get)$ ]]; then
          echo "::error::'key' and 'value' inputs are only valid for 'add' and 'update' actions." >&2
          exit 1
        fi
        
        if echo '${{ inputs.value }}' | jq -e 2>/dev/null; then
          echo "json_value=true" >> "$GITHUB_OUTPUT"
        else
          echo "json_value=false" >> "$GITHUB_OUTPUT"
        fi
        
        if [ -n "${{ inputs.org }}" ]; then
          echo "access_level=--org" >> "$GITHUB_OUTPUT"
          echo "level_name=${{ inputs.org }}" >> "$GITHUB_OUTPUT"
        elif [ -n "${{ inputs.env }}" ]; then
          echo "access_level=--env" >> "$GITHUB_OUTPUT"
          echo "level_name=${{ inputs.env }}" >> "$GITHUB_OUTPUT"
        else
          echo "access_level=--repo" >> "$GITHUB_OUTPUT"
          echo "level_name=${{ inputs.repo }}" >> "$GITHUB_OUTPUT"
        fi
        
        if [[ -n "$INPUT_PKGNAMES" ]]; then
          echo "lenpkg=$(printf '%s\n' "$INPUT_PKGNAMES" | wc -l)" >> "$GITHUB_OUTPUT"
        fi
        
        if [[ -n "$INPUT_KEYS" ]]; then
          echo "lenkey=$(printf '%s\n' "$INPUT_KEYS" | wc -l)" >> "$GITHUB_OUTPUT"
        fi
        
        if [[ -n "$INPUT_VALUES" ]]; then
          echo "lenval=$(printf '%s\n' "$INPUT_VALUES" | wc -l)" >> "$GITHUB_OUTPUT"
        fi
        
        echo "json_dict=$(gh variable get "$JSON_VAR_NAME" ${ACCESS_LEVEL} "$LEVEL_NAME" --json value --jq '.value')" >> "$GITHUB_OUTPUT"

        if ! $(echo "$JSON_VAR_NAME" | jq -c '.' 2>/dev/null); then
          echo "::error::inputs.json-in does not contain valid JSON data or is empty." >&2
          exit 1
        fi

    - name: Build Get Args
      id: build_get_args
      if: inputs.action == 'get'
      shell: bash
      env:
        JSON_DICT: "${{ steps.validate_inputs.outputs.json_dict }}"
        GH_TOKEN: "${{ inputs.gh-token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
        ACCESS_LEVEL: "${{ steps.validate_inputs.outputs.access_level }}"
        LEVEL_NAME: "${{ steps.validate_inputs.outputs.level_name }}"
        INPUT_PKGNAMES: "${{ inputs.pkg-name }}"
        INPUT_KEYS: "${{ inputs.key }}"
        LEN_PKGS: "${{ steps.validate_inputs.outputs.lenpkg }}"
        LEN_KEYS: "${{ steps.validate_inputs.outputs.lenkey }}"
        FILTER: '.packages'
      run: |
        args=()
        INPUT_PKGNAMES_ARR=()
        INPUT_KEYS_ARR=()
        
        INPUT_PKGNAMES="$(printf '%s\n' "$INPUT_PKGNAMES" | tr -d ' ')"
        INPUT_KEYS="$(printf '%s\n' "$INPUT_KEYS" | tr -d ' ')"
        
        for pkg in $INPUT_PKGNAMES; do INPUT_PKGNAMES_ARR+=("$pkg"); done
        for key in $INPUT_KEYS; do INPUT_KEYS_ARR+=("$key"); done
        
        # get_all_packages
        if [[ -z "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" ]]; then
          filter="$FILTER"
        
        # get_all_packages_with_keys
        elif [[ -z "$INPUT_PKGNAMES" && -n "$INPUT_KEYS" ]]; then
          filter="$FILTER | map_values({"
          for ((n=0; n<$LEN_KEYS; n++)); do
            [[ -z "${INPUT_KEYS_ARR[n]}" ]] && continue
            key="${INPUT_KEYS_ARR[n]}"
            args+=(--arg "key$n" "$key")
            filter+="\$key$n: .[\$key$n],"
          done
          filter="${filter%,}})"
        
        # get_packages_with_pkgnames
        elif [[ -n "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" ]]; then
          filter="$FILTER | {"
          for ((i=0; i<$LEN_PKGS; i++)); do
            [[ -z "${INPUT_PKGNAMES_ARR[i]}" ]] && continue
            pkgname="${INPUT_PKGNAMES_ARR[i]}"
            args+=(--arg "pkg$i" "$pkgname")
            filter+="\$pkg$i: .[\$pkg$i],"
          done
          filter="${filter%,}}"
        
        # get_packages_with_pkgname_and_keys
        elif [[ -n "$INPUT_PKGNAMES" && -n "$INPUT_KEYS" ]]; then
          filter="$FILTER | {"
          for ((i=0; i<$LEN_PKGS; i++)); do
            [[ -z "${INPUT_PKGNAMES_ARR[i]}" ]] && continue
            pkgname="${INPUT_PKGNAMES_ARR[i]}"
            args+=(--arg "pkg$i" "$pkgname")
            filter+="\$pkg$i: {"
            for ((n=0; n<$LEN_KEYS; n++)); do
              [[ -z "${INPUT_KEYS_ARR[n]}" ]] && continue
              key="${INPUT_KEYS_ARR[n]}"
              args+=(--arg "key$n" "$key")
              filter+="\$key$n: .[\$pkg$i][\$key$n],"
            done
            filter="${filter%,}},"
          done
          filter="${filter%,}}"
        
        else
          echo "Invalid input combination for 'get' action." >&2
          exit 1
        fi
        
        echo "out=$(jq -c "${args[@]}" "$filter" <<< "$JSON_DICT")" >> "$GITHUB_OUTPUT"
        echo "args=${args[*]}" >> "$GITHUB_OUTPUT"
        echo "filter='$(echo $filter | sed -e 's/\$/\\$/g')'" >> "$GITHUB_OUTPUT"
        
    
    - name: Build Add/Update Args
      id: build_add_args
      if: inputs.action == 'add' || inputs.action == 'update'
      shell: bash
      env:
        JSON_DICT: "${{ steps.validate_inputs.outputs.json_dict }}"
        GH_TOKEN: "${{ inputs.gh-token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
        ACCESS_LEVEL: "${{ steps.validate_inputs.outputs.access_level }}"
        LEVEL_NAME: "${{ steps.validate_inputs.outputs.level_name }}"
        INPUT_PKGNAMES: "${{ inputs.pkg-name }}"
        INPUT_KEYS: "${{ inputs.key }}"
        INPUT_VALUES: '${{ inputs.value }}'
        LEN_PKGS: "${{ steps.validate_inputs.outputs.lenpkg }}"
        LEN_KEYS: "${{ steps.validate_inputs.outputs.lenkey }}"
        LEN_VALS: "${{ steps.validate_inputs.outputs.lenval }}"
        FILTER: '.packages'
      run: |
        args=()
        INPUT_PKGNAMES_ARR=()
        INPUT_KEYS_ARR=()
        INPUT_VALUES_ARR=()
        
        INPUT_PKGNAMES="$(printf '%s\n' "$INPUT_PKGNAMES" | tr -d ' ')"
        INPUT_KEYS="$(printf '%s\n' "$INPUT_KEYS" | tr -d ' ')"
        INPUT_VALUES="$(printf '%s\n' "$INPUT_VALUES" | tr -d ' ')"
        
        for pkg in $INPUT_PKGNAMES; do INPUT_PKGNAMES_ARR+=("$pkg"); done
        for key in $INPUT_KEYS; do INPUT_KEYS_ARR+=("$key"); done
        for val in $INPUT_VALUES; do INPUT_VALUES_ARR+=("$val"); done

        # add_package_with_one_pkgname_and_multiple_keys_and_multiple_values
        if [[ -n "$INPUT_PKGNAMES" && -n "$INPUT_KEYS" && -n "$INPUT_VALUES" ]]; then
          filter="$FILTER + {\$pkg: {"
          pkgname="${INPUT_PKGNAMES_ARR[0]}"
          args+=(--arg "pkg" "$pkgname")
          for ((i=0; i<$LEN_KEYS; i++)); do
            [[ -z "${INPUT_KEYS_ARR[i]}" || -z "${INPUT_VALUES_ARR[i]}" ]] && continue
            key="${INPUT_KEYS_ARR[i]}"
            value="${INPUT_VALUES_ARR[i]}"
            args+=(--arg "key$i" "$key")
            args+=(--arg "val$i" "$value")
            filter+="\$key$i: \$val$i,"
          done
          filter="${filter%,}}}"
        
        # add_package_with_no_pkgname_and_multiple_values_and_no_keys
        elif [[ -z "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" && -n "$INPUT_VALUES" ]]; then
          filter="$FILTER + "
          for ((i=0; i<$LEN_VALS; i++)); do
            [[ -z "${INPUT_VALUES_ARR[i]}" ]] && continue
            value="${INPUT_VALUES_ARR[i]}"
            args+=(--argjson "val$i" "$value")
            filter+="\$val$i,"
          done
          filter="${filter%,}"
        
        # add_package_with_multiple_pkgnames_and_multiple_values_and_no_keys
        elif [[ -n "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" && -n "$INPUT_VALUES" ]]; then
          filter="$FILTER + {"
          for ((i=0; i<$LEN_PKGS; i++)); do
            [[ -z "${INPUT_PKGNAMES_ARR[i]}" || -z "${INPUT_VALUES_ARR[i]}" ]] && continue
            value=${INPUT_VALUES_ARR[i]}
            args+=(--arg "pkg$i" "${INPUT_PKGNAMES_ARR[i]}")
            args+=(--argjson "val$i" "$value")
            filter+="\$pkg$i: \$val$i,"
          done
          filter="${filter%,}}"
        
        else
          echo "Invalid input combination for 'update' action." >&2
          exit 1
        fi
        
        if jq -c "${args[@]}" "$filter" <<< "$JSON_DICT" | gh variable set "${{ inputs.json-in }}" ${ACCESS_LEVEL} "$LEVEL_NAME"; then
          echo "out=saved" >> "$GITHUB_OUTPUT"
        fi
        
        echo "args=${args[*]}" >> "$GITHUB_OUTPUT"
        echo "filter='$(echo $filter | sed -e 's/\$/\\$/g')'" >> "$GITHUB_OUTPUT"


    - name: Build Delete Args
      id: build_del_args
      if: inputs.action == 'delete' || inputs.action == 'remove'
      shell: bash
      env:
        JSON_DICT: "${{ steps.validate_inputs.outputs.json_dict }}"
        GH_TOKEN: "${{ inputs.gh-token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
        ACCESS_LEVEL: "${{ steps.validate_inputs.outputs.access_level }}"
        LEVEL_NAME: "${{ steps.validate_inputs.outputs.level_name }}"
        INPUT_PKGNAMES: "${{ inputs.pkg-name }}"
        INPUT_KEYS: "${{ inputs.key }}"
        LEN_PKGS: "${{ steps.validate_inputs.outputs.lenpkg }}"
        LEN_KEYS: "${{ steps.validate_inputs.outputs.lenkey }}"
        FILTER: '.packages'
      run: |
        args=()
        
        INPUT_PKGNAMES_ARR=()
        INPUT_KEYS_ARR=()
        
        INPUT_PKGNAMES="$(printf '%s\n' "$INPUT_PKGNAMES" | tr -d ' ')"
        INPUT_KEYS="$(printf '%s\n' "$INPUT_KEYS" | tr -d ' ')"
        
        for pkg in $INPUT_PKGNAMES; do INPUT_PKGNAMES_ARR+=("$pkg"); done
        for key in $INPUT_KEYS; do INPUT_KEYS_ARR+=("$key"); done
        
        # remove_packages_with_multiple_pkgnames
        if [[ -n "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" ]]; then
          filter="$FILTER | del("
          for ((i=0; i<$LEN_PKGS; i++)); do
            [[ -z "${INPUT_PKGNAMES_ARR[i]}" ]] && continue
            args+=(--arg "pkg$i" "${INPUT_PKGNAMES_ARR[i]}")
            filter+=".[\$pkg$i],"
          done
          filter="${filter%,})"
        
        # remove_from_one_package_multiple_keys
        elif [[ -n "$INPUT_PKGNAMES" && -n "$INPUT_KEYS" ]]; then
          filter="$FILTER |= (.[\$pkg] |= del("
          pkgname="${INPUT_PKGNAMES_ARR[0]}"
          args+=(--arg "pkg" "$pkgname")
          for ((i=0; i<$LEN_KEYS; i++)); do
            [[ -z "${INPUT_KEYS_ARR[i]}" ]] && continue
            key="${INPUT_KEYS_ARR[i]}"
            args+=(--arg "key$i" "$key")
            filter+=".[\$key$i],"
          done
          filter="${filter%,}))"
        
        else
          echo "Invalid input combination for 'remove' action." >&2
          exit 1
        fi

        if jq -c "${args[@]}" "$filter" <<< "$JSON_DICT" | gh variable set "${{ inputs.json-in }}" ${ACCESS_LEVEL} "$LEVEL_NAME"; then
          echo "out=saved" >> "$GITHUB_OUTPUT"
        fi
        
        echo "args=${args[*]}" >> "$GITHUB_OUTPUT"
        echo "filter='$(echo $filter | sed -e 's/\$/\\$/g')'" >> "$GITHUB_OUTPUT"

    - name: Convert output format
      id: convert_output
      if: inputs.output-structure == 'list' && inputs.action == 'get'
      shell: bash
      run: |
        if [ -n "${{ steps.build_get_args.outputs.out }}" ]; then
          echo "out=$(echo '${{ steps.build_get_args.outputs.out }}' | jq -c 'to_entries | map({name: .key} + .value)')" >> "$GITHUB_OUTPUT"
        else
          echo "out=[]" >> "$GITHUB_OUTPUT"
        fi
