name: "Export GPG Key"
description: "Export GPG Signing Key from GitHub Actions"
author: "DCx7C5"

inputs:
  public:
    required: false
    default: 'true'
    description: "Exports GPG public key"
  private:
    required: false
    default: 'false'
    description: "Exports GPG private key"
  pass:
    required: false
    default: ''
    description: "Passphrase for encrypted GPG key"
  export_sub:
    required: false
    default: 'true'
    description: "Exports only Subkey true/false"
  export_dir:
    required: false
    default: "${{ github.workspace }}/"
    description: "Directory path to exported GPG key"
  dcrypto:
    required: false
    default: 'false'
    description: "Uses dystopian-crypto management script"


runs:
  using: composite
  steps:
    - name: GPG Key export
      if: inputs.dcrypto != 'false'
      shell: bash
      run: |
        set -euo pipefail
        
        SUB=$([[ "${{ inputs.export_sub }}" == "true" ]] && echo "!")
        FPR=$(gpg --with-subkey-fingerprints --list-keys | tail -n2 | tr -d ' \n')        
        
        printf "${{ inputs.pass }}\n" | \
        gpg --batch \
            --pinentry-mode loopback \
            --passphrase-fd 0 \
            --export-secret-subkey "${FPR}${SUB}" > ${{ inputs.export_path }}
        echo "Subkey successfully exported"


    - name: Dystopian Crypto GPG Key Export
      shell: bash
      run: |
        set -euo pipefail
        
