#file: noinspection GithubFunctionSignatureValidation
name: "Push Docker Image to Registry"
description: "Push a Docker image to a registry (e.g., Docker Hub, GitHub Container Registry) with optional authentication and tagging"
author: "DCx7C5"


inputs:
  image_tag:
    description: "Name of the Docker image to push (e.g., 'my-image' or 'my-registry/my-image')"
    required: true
  image_version:
    description: "Version of the Docker image to push (defaults to 'latest')"
    required: true
    default: 'latest'
  registry:
    description: "URL of the Docker registry to push to (e.g., 'docker.io' for Docker Hub, 'ghcr.io' for GitHub Container Registry)"
    required: false
    default: 'ghcr.io'
  gh_token:
    description: "GitHub Token for authentication (required if pushing to GitHub Container Registry)"
    required: false
    default: ''
  working_directory:
    description: "Working directory for the action (defaults to github.workspace)"
    required: false
    default: ''
  user:
    description: "User name to create inside the container (defaults to runner.user)"
    required: false
    default: ${{ runner.user }}


runs:
  using: composite
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ toLower(inputs.user) || toLower(github.actor) || inputs.user || github.actor }}
        password: ${{ inputs.gh_token || env.GH_TOKEN || github.token }}

    - id: push_image
      shell: bash
      env:
        GH_TOKEN: "${{ inputs.gh_token || env.GH_TOKEN || github.token }}"
        USER: "${{ (inputs.user != '' && toLower(inputs.user)) || inputs.user || github.actor }}"
      run: |
        set -euo pipefail
        echo "image_name: '${{ inputs.image_tag }}'"
        echo "image_tag: '${{ inputs.image_version }}'"
        echo "registry: '${{ inputs.registry }}'"

        if [[ -z "${{ inputs.image_tag }}" || -z "${{ inputs.image_version }}" || -z "${{ inputs.registry }}" ]]; then
          echo "::error::image_tag, image_version, and registry inputs are required." >&2
          exit 1
        fi
        
        registry_url="${{ inputs.registry }}"
        registry_url="${registry_url%/}"
        repo="${{ github.repository }}"
        repo_name="${repo##*/}"
        full_image="$registry_url/${{ inputs.user || github.actor }}/${repo_name}/${{ inputs.image_tag }}:${{ inputs.image_version }}"

        docker tag "${{ inputs.image_tag }}:${{ inputs.image_version }}" "$full_image"
        echo ${{ inputs.gh_token || env.GH_TOKEN || github.token }} | docker login "$registry_url" -u ${{ toLower(github.actor) }} --password-stdin
        docker push "${full_image,,}"

    - name: Logout
      if: always()
      run: docker logout ghcr.io
      shell: bash
