name: "Manage GitHub Secret"
description: "Set a GitHub Secret from GitHub Actions (supports repository, organisation and environment secrets)"
author: "DCx7C5"


inputs:
  secret_name:
    required: true
    description: "Name of GitHub Secret to create or update"
  body:
    required: true
    description: "The value for the secret (reads from standard input if not specified)"
  env:
    required: false
    description: "Set deployment environment secret"
    default: ''
  org:
    required: false
    description: "Name of the repository/organisation/environment to store the secret in (defaults to current repository/organisation/environment based on variable_type)"
    default: ''
  repo:
    required: false
    description: "Set repository secret (defaults to current repository)"
    default: ${{ github.repository }}
  repos:
    required: false
    description: "New-line separated list of repositories to set the secret in (only for organisation secrets, defaults to all repositories in the organisation)"
    default: ''
  no_repos_select:
    required: false
    description: "Will not select any repositories to set the secret in"
    default: 'false'
  visibility:
    required: false
    description: "Visibility of the secret in the selected repositories (only for organisation secrets, (all|private|selected) defaults to 'all')"
    default: 'all'
  user:
    required: false
    description: "Set a user secret (GitHub Enterprise Server only)"
    default: 'false'
  app:
    required: false
    description: "Set the application for a secret: {actions|codespaces|dependabot}"
    default: ''

runs:
  using: composite
  steps:
    - name: Validate & Mask Inputs
      id: validate_and_mask
      shell: bash
      run: |
        set -euo pipefail
        if [[ -n '${{ inputs.body }}' ]]; then
          echo '::add-mask::${{ inputs.body }}'
        fi
        if [[ -n '${{ inputs.secret_name }}' ]]; then 
          echo '::add-mask::${{ inputs.secret_name }}'
        fi
        if [[ -n "${{ inputs.github_token }}" ]]; then 
          echo "::add-mask::${{ inputs.github_token }}"
        fi
      
        if [[ ! "${{ inputs.env != '' && 'true' }}${{ inputs.repo != '' && 'true' }}${{ inputs.org != '' && 'true' }}" =~ ^true$ ]]; then
          echo "::error::Not more than one of 'env', 'repo' or 'org' can be set to true or a non-empty value" >&2
          exit 1
        fi
        

    - name: Set GitHub Secret
      id: set_secret
      shell: bash
      env:
        GH_TOKEN: "${{ inputs.github_token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
        SECRET_NAME: "${{ inputs.secret_name }}"
        TYPE: ${{ case(
          inputs.env == 'true', "--env ${{ inputs.env || github.environment }}",
          inputs.org == 'true', "--org ${{ inputs.org || github.repository_owner }}", 
          inputs.repo == 'true', "--repo ${{ inputs.repo }}",
          '--repo ${{ inputs.repo }}' # default to repository secret if no type is explicitly set, for backward compatibility
          ) }}
      run: |
        set -euo pipefail
        
        GH_CMD+=(--${TYPE} "${{ inputs.ctx_name }}")
        if [[ "$TYPE" = 'org' ]]; then
          if [[ -n "${{ inputs.repositories }}" ]]; then
            GPG_CMD+=(--repos "$(echo "${{ inputs.repositories }}" | tr '\n' ',' | sed 's/,$//')")
          elif [[ "${{ inputs.no_repos_select }}" =~ ^true$ ]]; then
            GH_CMD+=(--no-repos-select)
          elif [[ "${{ inputs.visibility }}" =~ ^(all|private|selected)$ ]]; then
            GH_CMD+=(--visibility "${{ inputs.visibility }}")
          fi
        fi
        
        [[ "${{ inputs.user }}" == 'true' ]] && GH_CMD+=(--user)
        [[ -n "${{ inputs.app }}" ]] && GH_CMD+=(--app "${{ inputs.app }}")
        
        printf '%s' '${{ inputs.body }}' | gh secret set "$SECRET_NAME" "${GH_CMD[@]}" || {
          echo "::error::Failed to set GitHub Secret '$SECRET_NAME'" >&2
          exit 1
        }
