name: "Import GPG Keys"
description: "Import GPG Keys from GitHub Actions"
author: "DCx7C5 (fixed for 2025)"

inputs:
  enc_gpg:
    description: "SSL encrypted GPG private key (if from_secrets=false)"
    required: true
  pass:
    description: "Passphrase for encrypted GPG key (if from_secrets=false)"
    required: true


outputs:
  gpg_home:
    description: "Path to GNUPGHOME"
    value: ${{ steps.setup.outputs.gpg_home }}
  key_id:
    description: "Id of the imported GPG key"
    value: ${{ steps.gitconfig.outputs.key_id }}

runs:
  using: "composite"
  steps:
    - name: Setup GPG environment
      shell: bash
      id: setup
      run: |
        set -euo pipefail
        GNUPGHOME=$(mktemp -d /tmp/XXXXXXX)
        echo "GNUPGHOME=$GNUPGHOME" >> $GITHUB_ENV
        echo "gpg_home=$GNUPGHOME" >> $GITHUB_OUTPUT

    - name: Import GPG Keys (from inputs - pass as workflow inputs)
      id: import-secrets
      shell: bash
      env:
        GNUPGHOME: ${{ steps.setup.outputs.gpg_home }}
        GPG_PRIVATE_KEY: ${{ inputs.enc_gpg }}
        GPG_PASSPHRASE: ${{ inputs.pass }}   # Passed from workflow
      run: |
        set -euo pipefail
        openssl aes-256-cbc -a -d -pbkdf2 \
          -in <(echo "$GPG_PRIVATE_KEY") \
          -pass "pass:$GPG_PASSPHRASE" | \
        gpg --no-tty --batch --homedir "$GNUPGHOME" --import
        GPG_PRIVATE_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
        echo "$GPG_PRIVATE_KEY_ID:6:" | gpg --import-ownertrust --homedir "$GNUPGHOME"
        echo "Key $GPG_PRIVATE_KEY_ID imported and trusted."
        unset GPG_PRIVATE_KEY GPG_PASSPHRASE

    - name: Configure Git for GPG signing
      id: gitconfig
      shell: bash
      run: |
        set -euo pipefail
        GPG_PRIVATE_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
        GPG_MAIL=$(gpg --list-secret-keys "$GPG_PRIVATE_KEY_ID" | grep uid | head -1 | awk -F '<' '{print $2}' | awk -F '>' '{print $1}')
        GPG_NAME=$(gpg --list-secret-keys "$GPG_PRIVATE_KEY_ID" | grep uid | head -1 | awk -F '\\] ' '{print $2}' | awk '{print $1}')
        git config --global user.name "$GPG_NAME"
        git config --global user.email "$GPG_MAIL"
        git config --global user.signingkey "$GPG_PRIVATE_KEY_ID"
        git config --global commit.gpgsign true
        git config --global tag.gpgsign true
        git config --global tag.forceSignAnnotated true
        git config --global gpg.program gpg
        echo "key_id=$GPG_PRIVATE_KEY_ID" >> $GITHUB_OUTPUT