name: "Set new GPG passphrase"
description: "Set a new passphrase for a GPG key (using gpg)"
author: "DCx7C5"


inputs:
  key-id:
    required: true
    description: "GPG key ID to set the new passphrase for"
  new-passphrase:
    required: false
    description: "New passphrase to set for the GPG key"
    default: ''
  old-passphrase:
    required: false
    description: "Current passphrase for the GPG key (if needed)"
    default: ''
  gpg-home:
    required: false
    description: "Path to GPG home directory (optional, defaults to GNUPGHOME environment variable)"
    default: ''


runs:
  using: composite
  steps:
    - name: Set new GPG passphrase
      id: set_pass
      shell: bash
      env:
        GNUPGHOME: ${{ inputs.gpg-home || env.GNUPGHOME }}
      run: |
        set -euo pipefail
        
        gpg --batch --yes --no-tty --change-passphrase --pinentry-mode loopback --command-fd 0 <<'EOF'
        ${{ inputs.old-passphrase }}
        ${{ inputs.new-passphrase }}
        ${{ inputs.new-passphrase }}
        ${{ inputs.new-passphrase }}
        EOF
        
        echo "::notice::Passphrase for GPG key ID '${{ inputs.key-id }}' has been updated successfully."
