name: "Create GPG Signing Subkey"
description: "Create GPG Signing Key from GitHub Actions"
author: "DCx7C5"

inputs:
  time:
    description: "How long is key valid"
    required: true
  pass:
    description: "Passphrase for encrypted GPG key"
    required: true


runs:
  using: composite
  steps:
    - name: Generate SubKey
      shell: bash
      id: subkey_create
      run: |
        set -euo pipefail
        
        FPR=$(gpg --list-keys | head -2 | tail -1 | tr -d ' ')
        
        printf "${{ inputs.pass }}\n" | \
        gpg --batch \
            --pinentry-mode loopback \
            --passphrase-fd 0 \
            --homedir "$GNUPGHOME" \
            --quick-add-key "$FPR" \
            ed25519 sign ${{ inputs.time }}

    - name: Change Passphrase
      shell: bash
      run: |
        set -euo pipefail
        
        NEW_PASS=""
        echo "::add-mask::$NEW_PASS"
        NEW_PASS=$(tr -dc 'A-Za-z0-9!@.#$,\-\+%^&*' < /dev/urandom | head -c 32; echo)
        FPR=$(gpg --list-keys | head -2 | tail -1 | tr -d ' ')
        echo "new_pass=$NEW_PASS" 

        printf "${{ inputs.pass }}\n$NEW_PASS\n$NEW_PASS\n" | \
        gpg --batch \
            --yes \
            --pinentry-mode loopback \
            --passphrase-fd 0 \
            --homedir "$GNUPGHOME" \
            --command-fd 0 \
            --edit-key "$FPR" 'key 1' passwd save

    - name: Subkey export
      shell: bash
      run: |
        set -euo pipefail
        
        FPR=$(gpg --homedir "$GNUPGHOME" --with-subkey-fingerprints --list-keys | tail -n2 | tr -d ' \n')        
        printf "${{ inputs.pass }}\n" | \
        gpg --batch \
            --pinentry-mode loopback \
            --passphrase-fd 0 \
            --homedir "$GNUPGHOME" \
            --export-secret-subkey "${FPR}!" > subkey.gpg
        echo "Subkey successfully exported"

    - name: Upload secrets
      shell: bash
      run: |
        set -euo pipefail
        gh 
