name: "Store As GitHub Variable"
description: "Store as GitHub Variable from GitHub Actions"
author: "DCx7C5"

inputs:
  variable_name:
    required: true
    description: "Name of GitHub Variable to create or update"
  value:
    required: true
    description: "Value to store as GitHub Secret (can be multiline, e.g. for GPG keys)"
  scope:
    required: false
    description: "Scope of GitHub Variable (env or repo or org)"
    default: 'org'
  context:
    required: false
    description: "Name of the repository/organisation/environment to store the variable in (defaults to current repository/organisation/environment based on variable_type)"
    default: 'auto'
  github_token:
    required: false
    description: "GitHub Token with permissions to manage secrets (usually GITHUB_TOKEN)"
    default: ''


runs:
  using: composite
  steps:
    - name: Get scope context
      if: inputs.context == 'auto'
      id: get_scope_context
      shell: bash
      run: |
        set -euo pipefail
        if [[ "${{ inputs.scope }}" = "org" && "${{ github.repository }}" =~ ^.*/.*$ ]]; then
          org_from_repo="${{ github.repository }}" 
          org_from_repo="${org_from_repo%%/*}" 
          echo "::notice::No organisation input provided, using '${org_from_repo}' from repository context as organisation"
          echo "context=${org_from_repo}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ inputs.scope }}" = "env" && -n "${{ github.environment }}" ]]; then
          echo "::notice::No environment input provided, using "${{ github.environment }}" from repository context as environment"
          echo "context=${{ github.environment }}" >> "$GITHUB_OUTPUT"
        elif [ "${{ inputs.scope }}" = "repo" ]; then
          echo "::notice::No repository input provided, using "${{ github.repository }}" from repository context as repository"
          echo "context=${{ github.repository }}" >> "$GITHUB_OUTPUT"
        else
          echo "::error::The 'context' input is required for the selected variable scope '${{ inputs.scope }}'" >&2
          exit 1
        fi
        
        if [[ -n "${{ inputs.value }}" ]]; then
          echo "inputs_value=$(echo "${{ inputs.value }}" | jq '@json')" >> "$GITHUB_OUTPUT"
        fi

    - name: Store as GitHub Repo Variable
      if: inputs.scope == 'repo'
      id: store_as_repo_variable
      shell: bash
      env:
        INPUT_VALUE: "${{ steps.get_scope_context.outputs.inputs_value || inputs.value }}"
        GH_TOKEN: "${{ inputs.github_token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
      run: |
        set -euo pipefail
        gh variable set "${{ inputs.variable_name }}" --body "${INPUT_VALUE}" --repo "${{ steps.get_scope_context.outputs.context || inputs.context || github.repository }}" || {
          echo "::error::Failed to store variable ${{ inputs.variable_name }}" >&2
          exit 1 
        }
        
    - name: Store as GitHub Organisation Variable
      if: inputs.scope == 'org'
      id: store_as_org_variable
      shell: bash
      env:
        INPUT_VALUE: "${{ steps.get_scope_context.outputs.inputs_value || inputs.value }}"
        GH_TOKEN: "${{ inputs.github_token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
      run: |
        set -euo pipefail
        
        gh variable set "${{ inputs.variable_name }}" --body "${INPUT_VALUE}" --org "${{ steps.get_scope_context.outputs.context || inputs.context || github.repository_owner }}" --visibility all || {
          echo "::error::Failed to store variable ${{ inputs.variable_name }}" >&2
          exit 1 
        }

    - name: Store as GitHub Environment Variable
      if: inputs.scope == 'env'
      id: store_as_env_variable
      shell: bash
      env:
        INPUT_VALUE: "${{ steps.get_scope_context.outputs.inputs_value || inputs.value }}"
        GH_TOKEN: "${{ inputs.github_token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
      run: |
        set -euo pipefail
        gh variable set "${{ inputs.variable_name }}" --body "${INPUT_VALUE}" --env "${{ steps.get_scope_context.outputs.context || inputs.context || github.environment }}" || {
          echo "::error::Failed to store variable ${{ inputs.variable_name }}" >&2
          exit 1
        }
