name: "Create .SRCINFO file for AUR package"
description: "Generates a .SRCINFO file for an AUR package using makepkg"
author: "DCx7C5"


inputs:
  pkg_name:
    required: true
    description: "Name of the package to create .SRCINFO for (should match the directory name containing the PKGBUILD)"
  working_directory:
    required: false
    default: "${{ github.workspace || '.' }}"
    description: "Working directory to run makepkg in (default: the repository root or current directory if github.workspace is not set)"


runs:
  using: composite
  steps:
    - id: create_srcinfo
      uses: ./arch-run-cmd
      working-directory: "${{ inputs.working_directory }}"
      with:
        run_with_sudo: 'false'
        enable_ccache: 'false'
        preset_cache: 'false'
        run: cd "${{ inputs.pkg_name }}" && makepkg --printsrcinfo > .SRCINFO
