name: "Run updpkgsums to update PKGBUILD checksums"
description: "Runs updpkgsums on all PKGBUILD files to update their checksums"
author: "DCx7C5"


inputs:
  pkg_name:
    required: true
    description: "Name of the package to update"
  working_directory:
    required: false
    default: "${{ github.workspace || '.' }}"
    description: "Working directory to run updpkgsums in (default: package directory in the repository)"


runs:
  using: composite
  steps:
    - id: run_updpkgsums
      uses: ./arch-run-cmd
      working-directory: "${{ inputs.working_directory }}"
      with:
        run_with_sudo: 'false'
        enable_ccache: 'false'
        preset_cache: 'false'
        run: cd "${{ inputs.pkg_name }}" && updpkgsums
