name: "Import GPG Key"
description: "Import GPG Keys from GitHub Actions"
author: "DCx7C5"

inputs:
  gpg_priv:
    description: "GPG private key"
    required: true
  from_file:
    description: "To import from file"
    required: false
  from_secrets:
    description: "To import from secrets"
    required: false


outputs:
  gpg_home:
    description: "Path to GNUPGHOME"
    value: ${{ steps.setup.outputs.gpg_home }}

runs:
  using: composite
  steps:

    - name: Import GPG Key from secret
      id: import-secret
      if: inputs.from_secrets == 'true'
      shell: bash
      env:
        GPG_PRIVATE_KEY: ${{ inputs.enc_gpg }}
      run: |
        set -euo pipefail
        
        gpg --no-tty --batch --homedir "$GNUPGHOME" --import <(echo ${{ inputs.enc_gpg }})
        GPG_PRIVATE_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
        echo "$GPG_PRIVATE_KEY_ID:6:" | gpg --import-ownertrust --homedir "$GNUPGHOME"
        echo "Key $GPG_PRIVATE_KEY_ID imported and trusted."
        unset GPG_PRIVATE_KEY 

    - name: Import GPG from file
      id: import-file
      if: inputs.from_file == 'true'
      shell: bash
      run: |
        set -euo pipefail
        
        gpg --no-tty --batch --homedir "$GNUPGHOME" --import ${{ inputs.enc_gpg }}
        GPG_PRIVATE_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
        echo "$GPG_PRIVATE_KEY_ID:6:" | gpg --import-ownertrust --homedir "$GNUPGHOME"
        echo "Key $GPG_PRIVATE_KEY_ID imported and trusted."
        unset GPG_PRIVATE_KEY 
