name: "Create File Checksums"
description: "Create file checksums for release assets"
author: "DCx7C5"

inputs:
  files:
    description: "Files to create checksums for (default: all files in the repository)"
    required: false
    default: '*'
  b2sum:
    description: "Set to false to avoid creating b2 checksums"
    required: false
    default: 'true'
  sha512sum:
     description: "Set to false to avoid creating sha512 checksums"
     required: false
     default: 'false'


runs:
  using: composite
  steps:
    - id: sha512_checksums
      if: inputs.sha512sum == 'true'
      shell: bash
      run: |
        set -euo pipefail
        for file in *; do
          if [[ -f "$file" ]]; then
            sha512sum "$file" > "$file.sha512"
          fi
        done

    - id: b2_checksums
      if: inputs.b2sum == 'true'
      shell: bash
      run: |
        set -euo pipefail
        for file in *; do
          if [[ -f "$file" ]]; then
            b2sum "$file" > "$file.b2"
          fi
        done
