name: "Get latest Tag"
description: "Gets latest tag of a repository via GitHub Actions"
author: "DCx7C5"

inputs:
  repository:
    description: "The repository we search for the latest tag"
    required: false
    default: ${{ github.repository }}
  exit-if-not-found:
    description: "Whether to fail the action if no tag is found (default: false)"
    required: false
    default: 'false'
  exit-if-up-to-date:
    description: "Whether to fail the action if the latest tag is the same as the current tag (default: false)"
    required: false
    default: 'false'


outputs:
  tag_name:
    description: "Stores value of the latest tag (if found)"
    value: ${{ steps.tag_latest.outputs.tag_name }}

runs:
  using: composite
  steps:
    - name: Get latest tag
      id: tag_latest
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        GH_TOKEN: '${{ env.GH_TOKEN }}'
      run: |
        RESPONSE=$(curl -s -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          https://api.github.com/repos/$REPOSITORY/releases/latest)
        TAG=$(echo "$RESPONSE" | jq -r .tag_name)
        echo "tag_name=$TAG" >> "$GITHUB_OUTPUT"

    - name: Fail if latest tag is already up to date
      if: steps.tag_latest.outputs.tag_name != 'v1'
      shell: bash
      run: exit 0