name: "Test JSON Packages"

on:
  workflow_dispatch:
    inputs:
      pkgnames:
        description: "newline-separated list of package names to test (default: all packages in .ci/packages.json)"
        required: false
        default: ''
        type: string
  push:
    branches:
      - main
    paths:
      - ./aur-json-packages/action.yml
      - ./aur-json-packages/libpackages.sh
      - .github/workflows/test_json_pkgs.yml


jobs:
  test-json-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Get GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.DYSTOPIANBOT_APP_ID }}
          private-key: ${{ secrets.DYSTOPIANBOT_KEY }}
          owner: 'DystopianOS'


      - uses: actions/checkout@v6
        with:
          token: '${{ steps.app_token.outputs.token }}'

      - name: TEST
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          gh variable get JSON_PACKAGES --org DystopianOS 

      - name: Test JSON_PACKAGES
        id: get
        uses: ./aur-json-packages
        with:
          action: 'get'
          org: 'DystopianOS'
          gh-token: ${{ steps.app_token.outputs.token }}
          json_in: 'JSON_PACKAGES'
          pkg_name: |
            nvidia
            toolchain

      - id: check1
        run: |
          echo "Checking outputs..."
          echo '##### Args: ' >> "$GITHUB_STEP_SUMMARY"
          echo '```bash' >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.get.outputs.debug }} '${{ steps.get.outputs.debug-filter}}'" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          if [[ -n "${{ steps.get.outputs.out }}" ]]; then
            echo "Output from steps.get.outputs.out is available"
            echo "#### Output from steps.get.outputs.out" >> "$GITHUB_STEP_SUMMARY"
            echo '${{ steps.get.outputs.out }}' >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No output from steps.get.outputs.out"
            echo "#### No output from steps.get.outputs.out" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Test JSON_PACKAGES
        id: get_all
        uses: ./aur-json-packages
        with:
          action: 'get'
          org: 'DystopianOS'
          gh-token: ${{ steps.app_token.outputs.token }}
          json_in: 'JSON_PACKAGES'

      - id: check2
        run: |
          echo "Checking outputs..."
          echo '##### Args: ' >> "$GITHUB_STEP_SUMMARY"
          echo '```bash' >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.get_all.outputs.debug }} '${{ steps.get_all.outputs.debug-filter}}'" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          if [[ -n "${{ steps.get_all.outputs.out }}" ]]; then
            echo "Output from steps.get_all.outputs.out is available"
            echo "#### Output from steps.get_all.outputs.out" >> "$GITHUB_STEP_SUMMARY"
            echo '${{ steps.get_all.outputs.out }}' >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No output from steps.get_all.outputs.out"
            echo "#### No output from steps.get_all.outputs.out" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Test JSON_PACKAGES
        id: get_keys
        uses: ./aur-json-packages
        with:
          action: 'get'
          org: 'DystopianOS'
          gh-token: ${{ steps.app_token.outputs.token }}
          json_in: 'JSON_PACKAGES'
          pkg_name: |
            nvidia
            toolchain
          key: |
            submodule
            custom
            remote_dir

      - id: check3
        run: |
          echo "Checking outputs..."
          echo '##### Args: ' >> "$GITHUB_STEP_SUMMARY"
          echo '```bash' >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.get_keys.outputs.debug-args }} '${{ steps.get_keys.outputs.debug-filter}}'" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          
          if [[ -n "${{ steps.get_keys.outputs.out }}" ]]; then
            echo "Output from steps.get_keys.outputs.out is available"
            echo "##### Output from steps.get_keys.outputs.out" >> "$GITHUB_STEP_SUMMARY"
            echo '${{ steps.get_keys.outputs.out }}' >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No output from steps.get_keys.outputs.out"
            echo "#### No output from steps.get_keys.outputs.out" >> "$GITHUB_STEP_SUMMARY"
          fi