name: "Test JSON Packages"

on:
  workflow_dispatch:
    inputs:
      pkgnames:
        description: "newline-separated list of package names to test (default: all packages in .ci/packages.json)"
        required: false
        default: ''
        type: string
  push:
    branches:
      - main
    paths:
      - ./aur-json-packages/action.yml
      - ./aur-json-packages/libpackages.sh
      - .github/workflows/test_json_pkgs.yml


jobs:
  test-json-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Get GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.DYSTOPIANBOT_APP_ID }}
          private-key: ${{ secrets.DYSTOPIANBOT_KEY }}

      - uses: actions/checkout@v6
        with:
          token: '${{ steps.app_token.outputs.token }}'

      - name: Test JSON_PACKAGES
        id: get
        uses: ./aur-json-packages
        with:
          action: 'get'
          org: 'DystopianOS'
          gh-token: ${{ steps.app_token.outputs.token }}
          pkg_name: |
            nvidia
            toolchain

      - id: check
        run: |
          echo "Checking outputs..."
          if [[ -n "${{ steps.get.outputs.out }}" ]]; then
            echo "Output from steps.get.outputs.out is available"
            echo "### Output from steps.get.outputs.out" >> "$GITHUB_STEP_SUMMARY"
            echo '${{ steps.get.outputs.out }}' >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No output from steps.get.outputs.out"
            echo "### No output from steps.get.outputs.out" >> "$GITHUB_STEP_SUMMARY"
          fi
