name: "Test Everything SSL Action relevant to GPG Import"

on:
  workflow_dispatch:
    inputs:
      ssl_pass:
        description: "Passphrase to use for SSL decryption (if applicable)"
        required: false
        default: "pass"
        type: string
  push:
    branches:
      - main
    paths:
      - 'ssl-decrypt/action.yml'
      - 'ssl-encrypt/action.yml'
      - '.github/workflows/test_ssl.yml'


jobs:
  test-ssl-prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix_encrypt: ${{ steps.ssl_prepare.outputs.matrix_encrypt }}
      matrix_decrypt: ${{ steps.ssl_prepare.outputs.matrix_decrypt }}
    permissions:
      contents: write
      actions: write

    steps:
      - name: Prepare SSL-encrypted input
        id: ssl_prepare
        shell: bash
        run: |
          inputsl="${{ inputs.in || format('test') }}"
          inputml="$(printf '%s\n' "${{ inputs.in }}" "${{ inputs.in }}" "${{ inputs.in }}" "${{ inputs.in }}")"
          pass="${{ inputs.ssl_pass || secrets.GPG_PASSPHRASE }}"
          cat << EOF > test_encrypt.json
          [
            { "input": "$inputsl", "passphrase": "$pass", "input_type": "inline", "input_encoding": "text" },
            { "input": "$inputsl", "passphrase": "$pass", "input_type": "inline", "input_encoding": "base64" },
            { "input": "$inputsl", "passphrase": "$pass", "input_type": "inline", "input_encoding": "raw" },
            { "input": "$inputml", "passphrase": "$pass", "input_type": "file", "input_encoding": "text" },
            { "input": "$inputml", "passphrase": "$pass", "input_type": "file", "input_encoding": "base64" },
            { "input": "$inputml", "passphrase": "$pass", "input_type": "file", "input_encoding": "raw" }
          [   
          EOF 
              
          cat << EOF > test_decrypt.json
          [   
            { "input": "$inputsl", "passphrase": "$pass", "input_type": "inline", "input_encoding": "text" },
            { "input": "$inputsl", "passphrase": "$pass", "input_type": "inline", "input_encoding": "base64" },
            { "input": "$inputsl", "passphrase": "$pass", "input_type": "inline", "input_encoding": "raw" },
            { "input": "$inputml", "passphrase": "$pass", "input_type": "file", "input_encoding": "text" },
            { "input": "$inputml", "passphrase": "$pass", "input_type": "file", "input_encoding": "base64" },
            { "input": "$inputml", "passphrase": "$pass", "input_type": "file", "input_encoding": "raw" }
          [
          EOF
          echo "matrix_encrypt=$(jq -cr '.[]' test_encrypt.json)" >> "$GITHUB_OUTPUT"
          echo "matrix_decrypt=$(jq -cr '.[]' test_decrypt.json)" >> "$GITHUB_OUTPUT"
          

  test-ssl-encryption:
    needs:
      - test-ssl-prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    strategy:
      matrix:
        include: ${{ fromJson(needs.test-ssl-prepare.outputs.matrix_encrypt) }}
    steps:
      - name: Test SSL Encryption
        id: ssl_encrypt
        uses: ./ssl-encrypt
        with:
          passphrase: ${{ inputs.ssl_pass || secrets.SSL_PASSPHRASE || secrets.GPG_PASSPHRASE }}
          input_type: 'inline'
          input_encoding: 'text'
          in: ${{ inputs.in }}

      - name: Step Summary
        if: always()
        shell: bash
        run: |
          echo "### SSL Encryption Test" >> "$GITHUB_STEP_SUMMARY"
          echo "- Input Type: ${{ matrix.input_type }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Input Encoding: ${{ matrix.input_encoding }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Encrypted Output: ${{ steps.ssl_encrypt.outputs.encrypted_content }}" >> "$GITHUB_STEP_SUMMARY"
 

  test-sym-decryption:
    needs:
      - test-ssl-encryption
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    strategy:
      matrix:
        include: ${{ fromJson(needs.test-ssl-prepare.outputs.matrix_decrypt) }}
    steps:
      - name: Test SSL Decryption
        id: ssl_decrypt
        uses: ./ssl-decrypt
        with:
          passphrase: ${{ inputs.ssl_pass || secrets.SSL_PASSPHRASE || secrets.GPG_PASSPHRASE }}
          input_type: ${{ steps.ssl_encrypt.outputs.output_type }}
          input_encoding: ${{ steps.ssl_encrypt.outputs.output_encoding }}
          in: ${{ steps.ssl_encrypt.outputs.out }}

      - name: Step Summary
        if: always()
        shell: bash
        run: |
          echo "### SSL Decryption Test" >> "$GITHUB_STEP_SUMMARY"
          echo "- Input Type: ${{ matrix.input_type }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Input Encoding: ${{ matrix.input_encoding }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Output Type: ${{ steps.ssl_encrypt.outputs.type }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Output Encoding: ${{ steps.ssl_encrypt.outputs.output_encoding }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Decrypted Output: ${{ steps.ssl_decrypt.outputs.out }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Decryption Success: ${{ steps.ssl_decrypt.outputs.out == inputs.in }}" >> "$GITHUB_STEP_SUMMARY"
