on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write


jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} || ${{ github.token }}

      - name: Delete old Tag
        shell: bash
        run: |
          set -euo pipefail
          echo "Deleting old Tag"
          git tag --delete "v1" || true
          git push --delete origin "v1" || true
          echo "Tag successfully deleted everywhere"

      - name: Create new Tag and Release
        uses: DCx7C5/actions/create-tag-and-release@v1
        with:
          version: "1"
